# .github/workflows/deploy.yml
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            # start.sh에 실행 권한 주기
            chmod +x /home/ec2-user/3-sprint-mission/infra/ec2/start.sh
            # 배포 스크립트 실행
            bash /home/ec2-user/3-sprint-mission/infra/ec2/start.sh
